### PR TITLE
CurseForge autopackager support

### PR DESCRIPTION
**Pull request by SacredDuckwhale**
Just starting off simple to get things rolling :)

You'll have to set this up on the CF project site; using GitHub webhooks you can automatically deploy tagged versions to the network, but you'll want to have libraries be added by them as opposed to keeping a rigid copy in the repository. I've added the currently used libraries and removed the actual files (keep a local copy and use symbolic links for local testing).

README.MD doesn't yet exist, but you can create it and use the same HTML or Markup file in the project's description (on Curse). If you don't want to do that, I guess the line can be removed.

The dump() change was just for me, It think reinventing the wheel isn't necessary, but you can always delete it. Edit: I reverted it and will submit a separate pull request for QoL changes later to make sure things don't get too confusing.

PS: The packager is quite fragile, and typos/symbols will break it if you aren't careful. It won't usually tell you what exactly it disliked, but you can see the build failing (= not deploying) via the CurseForge dashbord > builds. Since the config file doesn't need frequent changes, that isn't too bad given the advantages it provides. As I don't have access to the CF project site, you will have to test this version and hope I didn't have a typo somewhere - sorry X_X

### CODE REVIEW

**Comment by chancedj** [comment]
Thanks.  Appreciate the help in what you've done.  I've tagged this for milestone 1.2 since that is what i currently had setup to begin the localization project :).

**Comment by chancedj** [comment]
also, w/r to the dump() vs printTable - the only advantage the printTable had for me over dump was that it allowed me to exit after a max depth.  So if i only wanted to go nested in 2 time,s i could stop it at that.  But i'm far enough along now that i shouldn't have to go through and start refactoring the entiredb - so it should be moot at this point.

**Comment by SacredDuckwhale** [comment]
It's really just laying the groundwork - you can add AceLocale before you write any textual output that would have to be localized and it won't impact the workflow much.

dump() has a max depth of 30 (I think), but nesting that deeply is usually unnecessary. It isn't part of the changes, I simply prefer its visual representation :)

If you want to merge this, all you have to do is set up the GitHub webhook [see CurseForge docs](https://www.curseforge.com/docs/packaging) and copy the ignored library files manually, once. You can create a symbolic link (mklink.exe on Windows) in the addons folder, for convenience, but that's personal preference.

**Comment by SacredDuckwhale** [comment]
Patch applied to resolve merge conflicts - no big deal :)

Tagging @chancedj for visibility (probably not necessary, but well...)

**Comment by chancedj** [comment]
Merged PR to resolve issue #7

**Pull request merged**
